#!/bin/bash
arch=`uname -m`
echo $arch #Debug

versions=$(curl -sb -H "Accept: application/json" "https://teamspeak.com/versions/client.json")

version=$(echo $versions | jq -r ".linux.$arch.version")
checksum=$(echo $versions | jq -r ".linux.$arch.checksum")
mirror=$(echo $versions | jq -r ".linux.$arch.mirrors[\"teamspeak.com\"]")

echo $mirror #Debug

run="teamspeak3client.run"

cd /tmp
curl -o $run $mirror

bash $run
mv Teamspeak3-Client-linux_$arch /opt/teamspeak3client #TODO: Check, if foldername ist really Teamspeak3-Client-linux_$arch in any case

rm -f $run
