#!/bin/bash
arch=`uname -m`
echo $arch

versions=$(curl -sb -H "Accept: application/json" "https://teamspeak.com/versions/client.json")
versionInfo=$(echo $versions | jq "[.linux.$arch.version, .linux.$arch.checksum, .linux.$arch.mirrors[\"teamspeak.com\"]]")

echo $versionInfo
